sudo: required
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ci/linux-deps.sh; fi

before_script:
  # Fake display
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - sudo apt-get install libsndfile1

  # Set PROJUCER to GPL mode
  - cd $TRAVIS_BUILD_DIR/3rd_party/JUCE
  - cd extras/Projucer/JuceLibraryCode
  - pwd
  - sed -i "s/#define JUCER_ENABLE_GPL_MODE 0/#define JUCER_ENABLE_GPL_MODE 1/" AppConfig.h
  - sed -i "s/#define JUCE_USE_DARK_SPLASH_SCREEN 1/#define JUCE_USE_DARK_SPLASH_SCREEN 0/" AppConfig.h
  - sed -i "s/#define JUCE_WEB_BROWSER 1/#define JUCE_WEB_BROWSER 0/" AppConfig.h
  - cat AppConfig.h

  # Build PROJUCER
  - cd ../Builds/LinuxMakefile
  - make -j4 CONFIG=Release
  - cd $TRAVIS_BUILD_DIR

script:
  # Set gcc version
  - ls
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ci/linux-env.sh; fi

  # Generate Makefile
  - $TRAVIS_BUILD_DIR/3rd_party/JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave $TRAVIS_BUILD_DIR/modEQ.jucer
  
  # Build
  - cd Builds/LinuxMakefile
  - make -j4 CONFIG=Release

# os: osx
# sudo: false
# language: cpp

# before_install:
#   - gem install xcpretty
#   - gem install xcpretty-travis-formatter
#   - cd $TRAVIS_BUILD_DIR
#   - git clone https://github.com/WeAreROLI/JUCE.git
#   - git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
#   - cd JUCE
#   - git checkout tags/5.3.2
#   - cd extras/Projucer/JuceLibraryCode
#   - pwd
#   - sed -i '' "s/#define JUCER_ENABLE_GPL_MODE 0/#define JUCER_ENABLE_GPL_MODE 1/" AppConfig.h
#   - sed -i '' "s/#define JUCE_USE_DARK_SPLASH_SCREEN 1/#define JUCE_USE_DARK_SPLASH_SCREEN 0/" AppConfig.h
#   - sed -i '' "s/#define JUCE_WEB_BROWSER 1/#define JUCE_WEB_BROWSER 0/" AppConfig.h
#   - cat AppConfig.h
#   - cd $TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/MacOSX/
#   - xcodebuild -project Projucer.xcodeproj | xcpretty -f `xcpretty-travis-formatter`  > /dev/null

# script:
#   - cd $TRAVIS_BUILD_DIR/
#   - export PROJUCER=$TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/MacOSX/build/Debug/Projucer.app/Contents/MacOS/Projucer
#   # - $PROJUCER --set-global-search-path osx defaultJuceModulePath  $TRAVIS_BUILD_DIR/JUCE/modules
#   # - $PROJUCER --resave modEQ.jucer
#   # - cd $TRAVIS_BUILD_DIR/Builds/MacOSX/
#   # - ls
#   # - xcodebuild -project modEQ.xcodeproj/ clean
#   # - xcodebuild -project modEQ.xcodeproj/ ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO -configuration Release | xcpretty -f `xcpretty-travis-formatter` > /dev/null
#   - echo "SUCESS"
