dist: trusty
sudo: false
language: cpp
compiler:
  - gcc
  # - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8
      - freeglut3-dev g++
      - libasound2-dev
      - libcurl4-openssl-dev
      - libfreetype6-dev
      - libjack-jackd2-dev
      - libx11-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxrandr-dev
      - mesa-common-dev
      - ibwebkit2gtk-4.0-dev

before_install:
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/WeAreROLI/JUCE.git
  - git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
  - cd JUCE
  - git checkout tags/5.3.2
  - cd extras/Projucer/JuceLibraryCode
  - sed -i '' "s/#define JUCER_ENABLE_GPL_MODE 1/#define JUCER_ENABLE_GPL_MODE 1/" AppConfig.h
  - sed -i '' "s/#define JUCE_USE_DARK_SPLASH_SCREEN 1/#define JUCE_USE_DARK_SPLASH_SCREEN 0/" AppConfig.h
  - cat AppConfig.h
  - cd $TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/LinuxMakefile/
  - make config=Release -j2

install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  # - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

script:
  - echo "SUCESS"

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
