branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-documentation
    - cd $TRAVIS_BUILD_DIR
    - make documentation

  - &script-macOS
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake --version
    - cmake -GXcode -DCMAKE_BUILD_TYPE:STRING=Release ..
    - cmake --build . --config Release | xcpretty -f `xcpretty-travis-formatter`

#    # Build Project
#    - cd $TRAVIS_BUILD_DIR/Builds/MacOSX/
#    - ls
#    - xcodebuild -project modEQ.xcodeproj/ clean
#    - xcodebuild -project modEQ.xcodeproj/ ARCHS="x86_64" ONLY_ACTIVE_ARCH=NO -configuration Release | xcpretty -f `xcpretty-travis-formatter`
#    - ls -la build/Release

#    # Test / PluginVal
#    - mkdir -p $TRAVIS_BUILD_DIR/PluginVal/bin
#    - cd $TRAVIS_BUILD_DIR/PluginVal
#    - curl -L "https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_macOS.zip" -o pluginval.zip
#    - unzip pluginval
#    - pluginval.app/Contents/MacOS/pluginval --validate-in-process --output-dir "./bin" --strictness-level 10 --validate "$TRAVIS_BUILD_DIR/Builds/MacOSX/build/Release/modEQ.vst3" || exit 1
#    - ls bin
#
#    # Package
#    - cd $TRAVIS_BUILD_DIR/Builds/MacOSX/
#    - zip -r modEQ-$(git describe --tags --abbrev=0)-macOS.zip build/Release -x build/Release/libmodEQ.a

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      script: *script-macOS

      # deploy:
      #   provider: releases
      #   api_key: $GITHUB_TOKEN
      #   file: $TRAVIS_BUILD_DIR/Builds/MacOSX/modEQ-$(git describe --tags --abbrev=0)-macOS.zip
      #   skip_cleanup: true
      #   on:
      #     all_branches: true

    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      script: *script-documentation
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: $TRAVIS_BUILD_DIR/build_documentation/html
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
