sudo: required
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get update -qq
  - sudo apt-get install -y
    libfreetype6-dev
    libx11-dev
    libstdc++6
    libc++-dev
    libxinerama-dev
    libxrandr-dev
    libxcursor-dev
    libxcomposite-dev
    mesa-common-dev
    libasound2-dev
    freeglut3-dev
    libcurl4-gnutls-dev+
    libasound2-dev
    libsndfile1
    libjack-dev
  - sudo add-apt-repository -y ppa:webkit-team/ppa
  - sudo apt-get update
  - sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
  - sudo apt-get update --fix-missing

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - sudo apt-get install libsndfile1

  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/WeAreROLI/JUCE.git
  - git clone --recursive https://github.com/steinbergmedia/vst3sdk.git

  - cd JUCE
  - git checkout tags/5.3.2
  - cd extras/Projucer/JuceLibraryCode
  - pwd
  - sed -i "s/#define JUCER_ENABLE_GPL_MODE 0/#define JUCER_ENABLE_GPL_MODE 1/" AppConfig.h
  - sed -i "s/#define JUCE_USE_DARK_SPLASH_SCREEN 1/#define JUCE_USE_DARK_SPLASH_SCREEN 0/" AppConfig.h
  - sed -i "s/#define JUCE_WEB_BROWSER 1/#define JUCE_WEB_BROWSER 0/" AppConfig.h
  - cat AppConfig.h

  - cd ../Builds/LinuxMakefile
  - make -j4 CONFIG=Release
  - cd $TRAVIS_BUILD_DIR

script:
  - cd $TRAVIS_BUILD_DIR
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - gcc -v && g++ -v && cmake --version
  - ls
  - $TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --set-global-search-path linux defaultJuceModulePath $TRAVIS_BUILD_DIR/JUCE/modules
  - $TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave $TRAVIS_BUILD_DIR/modEQ.jucer
  - ls
  - cd Builds/LinuxMakefile
  - make -j4 CONFIG=Release

# os: osx
# sudo: false
# language: cpp

# before_install:
#   - gem install xcpretty
#   - gem install xcpretty-travis-formatter
#   - cd $TRAVIS_BUILD_DIR
#   - git clone https://github.com/WeAreROLI/JUCE.git
#   - git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
#   - cd JUCE
#   - git checkout tags/5.3.2
#   - cd extras/Projucer/JuceLibraryCode
#   - pwd
#   - sed -i '' "s/#define JUCER_ENABLE_GPL_MODE 0/#define JUCER_ENABLE_GPL_MODE 1/" AppConfig.h
#   - sed -i '' "s/#define JUCE_USE_DARK_SPLASH_SCREEN 1/#define JUCE_USE_DARK_SPLASH_SCREEN 0/" AppConfig.h
#   - sed -i '' "s/#define JUCE_WEB_BROWSER 1/#define JUCE_WEB_BROWSER 0/" AppConfig.h
#   - cat AppConfig.h
#   - cd $TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/MacOSX/
#   - xcodebuild -project Projucer.xcodeproj | xcpretty -f `xcpretty-travis-formatter`  > /dev/null

# script:
#   - cd $TRAVIS_BUILD_DIR/
#   - export PROJUCER=$TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/MacOSX/build/Debug/Projucer.app/Contents/MacOS/Projucer
#   # - $PROJUCER --set-global-search-path osx defaultJuceModulePath  $TRAVIS_BUILD_DIR/JUCE/modules
#   # - $PROJUCER --resave modEQ.jucer
#   # - cd $TRAVIS_BUILD_DIR/Builds/MacOSX/
#   # - ls
#   # - xcodebuild -project modEQ.xcodeproj/ clean
#   # - xcodebuild -project modEQ.xcodeproj/ ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO -configuration Release | xcpretty -f `xcpretty-travis-formatter` > /dev/null
#   - echo "SUCESS"

# LINUX
# - sed -i "s/#define JUCER_ENABLE_GPL_MODE 0/#define JUCER_ENABLE_GPL_MODE 1/" AppConfig.h
# - sed -i "s/#define JUCE_USE_DARK_SPLASH_SCREEN 1/#define JUCE_USE_DARK_SPLASH_SCREEN 0/" AppConfig.h
# - sed -i "s/#define JUCE_WEB_BROWSER 1/#define JUCE_WEB_BROWSER 0/" AppConfig.h

# install:
#   - "[ $CXX = g++ ] && export CXX=g++-6 || true"
#   # - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

# compiler:
#   - gcc
#   # - clang
