dist: trusty
sudo: false
language: cpp
compiler:
  - gcc
  # - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - llvm
      - clang-3.8
      - freeglut3-dev
      - libasound2-dev
      - libcurl4-openssl-dev
      - libfreetype6-dev
      - libjack-jackd2-dev
      - libx11-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxrandr-dev
      - mesa-common-dev

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/WeAreROLI/JUCE.git
  - git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
  - cd JUCE
  - git checkout tags/5.3.2
  - cd extras/Projucer/JuceLibraryCode
  - pwd
  - sed -i "s/#define JUCER_ENABLE_GPL_MODE 0/#define JUCER_ENABLE_GPL_MODE 1/" AppConfig.h
  - sed -i "s/#define JUCE_USE_DARK_SPLASH_SCREEN 1/#define JUCE_USE_DARK_SPLASH_SCREEN 0/" AppConfig.h
  - sed -i "s/#define JUCE_WEB_BROWSER 1/#define JUCE_WEB_BROWSER 0/" AppConfig.h
  - cat AppConfig.h
  - cd $TRAVIS_BUILD_DIR/JUCE/extras/Projucer/Builds/LinuxMakefile/

install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  # - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

script:
  - echo "SUCESS"
