# GENERAL
version: 0.4.0.{build}
branches:
  only:
    - master
image:
  - Visual Studio 2017
clone_folder: c:\modEQ

# SETUP
install:
  - cmd: mkdir C:\VSTPlugIns
  - cmd: mkdir C:\VSTPlugIns\tobanteAudio
  - cmd: cd c:\modEQ
  - cmd: git submodule update --init --recursive
  - ps: (Get-Content -Path "c:/modEQ/3rd_party/JUCE/extras/Projucer/JuceLibraryCode/AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCER_ENABLE_GPL_MODE 0", "#define JUCER_ENABLE_GPL_MODE 1"} | Set-Content -Path "c:/modEQ/3rd_party/JUCE/extras/Projucer/JuceLibraryCode/AppConfig.h"
  - cmd: msbuild c:/modEQ/3rd_party/JUCE/extras/Projucer/Builds/VisualStudio2017/Projucer.sln /property:Platform=x64 /m
  - cmd: c:\modEQ\3rd_party\JUCE\extras\Projucer\Builds\VisualStudio2017\x64\Debug\App\Projucer.exe --resave C:\modEQ\modEQ.jucer

# BUILD
build_script:
  - cmd: msbuild c:/modEQ/Builds/VisualStudio2017/modEQ.sln /p:Platform=x64 /p:Configuration=Release /m
  - cmd: cd c:\modEQ
  - cmd: mkdir bin
  - cmd: powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_Windows.zip -OutFile pluginval.zip"
  - cmd: powershell -Command "Expand-Archive pluginval.zip -DestinationPath ."
  - cmd: pluginval.exe --validate-in-process --output-dir "./bin" --validate "c:/modEQ/Builds/VisualStudio2017/x64/Release/VST3/modEQ.vst3"
  - cmd: if %ERRORLEVEL% neq 0 exit /b 1
  - cmd: 7z a modEQ-win.zip c:/modEQ/Builds/VisualStudio2017/x64/Release/VST3/modEQ.vst3

# deploy:
#   release: modEQ-v$(appveyor_build_version)-win64
#   description: 'tobanteAudio modEQ'
#   provider: GitHub
#   auth_token:
#     secure: C291gStpG222iqDbixH3ddeM+BE9CMp+leZsI177GsB9oIWhJcyZEn+qChtc7p8T
#   artifact: c:\modEQ\modEQ-win.zip
#   draft: false
#   prerelease: false
#   on:
#     branch: master
