image:
  - Visual Studio 2017
clone_folder: c:/modEQ
install:
  - ps: cd c:/
  - ps: git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
  - ps: git clone https://github.com/WeAreROLI/JUCE.git
  - ps: dir
  - ps: cd c:/JUCE/
  - ps: git checkout tags/5.3.2
  - ps: cd c:/JUCE/extras/Projucer/JuceLibraryCode
  - ps: (Get-Content -Path "AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCER_ENABLE_GPL_MODE 1", "#define JUCER_ENABLE_GPL_MODE 0"} | Set-Content -Path "AppConfig.h"
  - ps: (Get-Content -Path "AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCE_USE_DARK_SPLASH_SCREEN 1", "#define JUCE_USE_DARK_SPLASH_SCREEN 0"} | Set-Content -Path "AppConfig.h"
  - ps: cd c:\JUCE\extras\Projucer\Builds\VisualStudio2017
  - ps: msbuild Projucer.sln /property:Platform=x64

before_build:
  - ps: cd c:\JUCE\extras\Projucer\Builds\VisualStudio2017\x64\Debug\App
  - ps: ./Projucer --set-global-search-path windows defaultJuceModulePath c:/JUCE/modules
  - ps: ./Projucer --set-global-search-path windows vst3path c:/vst3sdk
  - ps: ./Projucer --resave c:/modEQ/modEQ.jucer

build_script:
  - ps: cd c:\modEQ\Builds\VisualStudio2017
  - ps: msbuild modEQ.sln /property:Platform=x64
